version: '2'
services:

  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    ports:
      - "8000:8000"


  sampledynamodbcode:
    build: .
    depends_on:
      - dynamodb
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
      AWS_REGION: ${AWS_REGION}
      JAVA_OPTS: -Xmx192m

    
